-- migration: media_galleries_and_app_bucket_rls
-- purpose: enable RLS on media_items, galleries, gallery_media_items; create storage buckets
--          media-items and app-media-items; add storage and table RLS policies.
-- affected: public.media_items, public.galleries, public.gallery_media_items, storage.buckets, storage.objects
-- note: table DDL is in supabase/schemas/; this migration covers RLS and storage (caveats for declarative diff).
-- run order: apply after the schema migration that creates the tables (generated by db diff). timestamp 20261231235959 ensures this runs last.

-- =============================================================================
-- storage buckets
-- =============================================================================

-- bucket: user/vendor uploads (private). path: users/{user_id}/{year}/{month}/{uuid}-{filename}
-- ownership enforced by storage RLS using path segment index 2 for user_id.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'media-items',
  'media-items',
  false,
  104857600,
  array['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/heic', 'video/mp4', 'video/mov', 'video/avi', 'video/quicktime']
)
on conflict (id) do nothing;

-- bucket: app-owned public media (public read). path: {year}/{month}/{uuid}-{filename}
-- no user segment; write restricted to super_admin via storage RLS.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'app-media-items',
  'app-media-items',
  true,
  104857600,
  array['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/heic', 'video/mp4', 'video/mov', 'video/avi', 'video/quicktime']
)
on conflict (id) do nothing;

-- =============================================================================
-- storage RLS: media-items (path index 2 = user_id for users/{user_id}/...)
-- =============================================================================

create policy "Users can upload their own media items"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'media-items' and (auth.uid())::text = (storage.foldername(name))[2]);

create policy "Users can view all media items"
  on storage.objects for select to authenticated
  using (bucket_id = 'media-items');

create policy "Users can update their own media items"
  on storage.objects for update to authenticated
  using (bucket_id = 'media-items' and (auth.uid())::text = (storage.foldername(name))[2])
  with check (bucket_id = 'media-items' and (auth.uid())::text = (storage.foldername(name))[2]);

create policy "Users can delete their own media items"
  on storage.objects for delete to authenticated
  using (bucket_id = 'media-items' and (auth.uid())::text = (storage.foldername(name))[2]);

-- =============================================================================
-- storage RLS: app-media-items (super_admin write; anon + authenticated read)
-- =============================================================================

create policy "Anon can view app media items"
  on storage.objects for select to anon
  using (bucket_id = 'app-media-items');

create policy "Authenticated can view app media items"
  on storage.objects for select to authenticated
  using (bucket_id = 'app-media-items');

create policy "Super admin can insert app media items"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'app-media-items' and exists (select 1 from public.user_profiles where id = auth.uid() and app_role = 'super_admin'));

create policy "Super admin can update app media items"
  on storage.objects for update to authenticated
  using (bucket_id = 'app-media-items' and exists (select 1 from public.user_profiles where id = auth.uid() and app_role = 'super_admin'))
  with check (bucket_id = 'app-media-items' and exists (select 1 from public.user_profiles where id = auth.uid() and app_role = 'super_admin'));

create policy "Super admin can delete app media items"
  on storage.objects for delete to authenticated
  using (bucket_id = 'app-media-items' and exists (select 1 from public.user_profiles where id = auth.uid() and app_role = 'super_admin'));

-- =============================================================================
-- table RLS: media_items
-- =============================================================================

alter table public.media_items enable row level security;

-- authenticated can see all rows; anon only rows where is_public = true (for landing page / ImageKit URLs)
create policy "Authenticated can view all media items"
  on public.media_items for select to authenticated using (true);

create policy "Anon can view public media items"
  on public.media_items for select to anon using (is_public = true);

-- insert: own uploads or super_admin for app bucket
create policy "Users can create own or app media items (super_admin)"
  on public.media_items for insert to authenticated
  with check (
    uploader_id = auth.uid()
    or (bucket_id = 'app-media-items' and exists (select 1 from public.user_profiles where id = auth.uid() and app_role = 'super_admin'))
  );

create policy "Users can update own or app media items (super_admin)"
  on public.media_items for update to authenticated
  using (
    uploader_id = auth.uid()
    or (bucket_id = 'app-media-items' and exists (select 1 from public.user_profiles where id = auth.uid() and app_role = 'super_admin'))
  )
  with check (
    uploader_id = auth.uid()
    or (bucket_id = 'app-media-items' and exists (select 1 from public.user_profiles where id = auth.uid() and app_role = 'super_admin'))
  );

create policy "Users can delete own or app media items (super_admin)"
  on public.media_items for delete to authenticated
  using (
    uploader_id = auth.uid()
    or (bucket_id = 'app-media-items' and exists (select 1 from public.user_profiles where id = auth.uid() and app_role = 'super_admin'))
  );

-- =============================================================================
-- table RLS: galleries
-- =============================================================================

alter table public.galleries enable row level security;

create policy "Authenticated can view own or public galleries"
  on public.galleries for select to authenticated
  using (creator_id = auth.uid() or is_public = true);

create policy "Authenticated can create own galleries"
  on public.galleries for insert to authenticated
  with check (creator_id = auth.uid());

create policy "Authenticated can update own galleries"
  on public.galleries for update to authenticated
  using (creator_id = auth.uid())
  with check (creator_id = auth.uid());

create policy "Authenticated can delete own galleries"
  on public.galleries for delete to authenticated
  using (creator_id = auth.uid());

-- =============================================================================
-- table RLS: gallery_media_items
-- =============================================================================

alter table public.gallery_media_items enable row level security;

create policy "Authenticated can view gallery media when gallery visible"
  on public.gallery_media_items for select to authenticated
  using (
    exists (select 1 from public.galleries g where g.id = gallery_id and (g.creator_id = auth.uid() or g.is_public = true))
  );

create policy "Authenticated can add to gallery when creator"
  on public.gallery_media_items for insert to authenticated
  with check (exists (select 1 from public.galleries g where g.id = gallery_id and g.creator_id = auth.uid()));

create policy "Authenticated can update gallery media when gallery creator"
  on public.gallery_media_items for update to authenticated
  using (exists (select 1 from public.galleries g where g.id = gallery_id and g.creator_id = auth.uid()))
  with check (exists (select 1 from public.galleries g where g.id = gallery_id and g.creator_id = auth.uid()));

create policy "Authenticated can delete gallery media when gallery creator"
  on public.gallery_media_items for delete to authenticated
  using (exists (select 1 from public.galleries g where g.id = gallery_id and g.creator_id = auth.uid()));

-- =============================================================================
-- optional comments (not tracked by schema diff)
-- =============================================================================

comment on column public.media_items.file_path is 'Path relative to the bucket in bucket_id. For media-items: users/{user_id}/{year}/{month}/{uuid}-{filename}. For app-media-items: {year}/{month}/{uuid}-{filename}.';
comment on column public.media_items.bucket_id is 'Storage bucket: media-items (user/vendor uploads) or app-media-items (app-owned public media, super_admin only write).';
